scalar Time

type Query {
  currentIdentity: Identity!
}

type Mutation {
  signUp(input: PasswordInput!): Identity!
  signInWithPassword(input: PasswordInput!): Token!
}

type Token {
  type: String!
  idToken: String!
  expiresAt: Time!
}

type Identity {
  id: ID!
}

input PasswordInput {
  email: String
  username: String
  phone: String
  password: String!
}