scalar Time

type Query {
  strategies: [Strategy!]!
  currentIdentity: Identity!
}

type Mutation {
  signUp(input: PasswordInput!): Identity!
  signInWithPassword(input: PasswordInput!): Token!
}

type Token {
  type: String!
  idToken: String!
  expiresAt: Time!
}

type Identity {
  id: ID!
}

interface Strategy {
  type: StrategyType!
}

type StrategyOAuth implements Strategy {
  type: StrategyType!
  providers: [String!]!
}

type StrategyPassword implements Strategy {
  type: StrategyType!
}

enum StrategyType {
  OAUTH
  PASSWORD
}

input PasswordInput {
  email: String
  username: String
  phone: String
  password: String!
}