type Query {
  strategies: [Strategy!]!
}

interface Strategy {
  type: StrategyType!
}

type StrategyOAuth implements Strategy {
  type: StrategyType!
  providers: [String!]!
}

type StrategyPassword implements Strategy {
  type: StrategyType!
}

enum StrategyType {
  OAUTH
  PASSWORD
}